### ISSUE TITLE
[ENHANCEMENT] Containerize Application (Docker, Kubernetes)

### ISSUE THREAD

**Issue by ahmadk953** [ahmadk953/threads-clone#43]
> [!WARNING}
> This is just a quick draft, and nothing here is final. Also, don't expect this feature to be released any time soon.

## Why do I want to do this?
I know this is not necessary and overkill for this project but, I want to do this because of a few things:
1. High Availability - For production use
2. Learning new things - I have never created a Kubernetes image before and as for Docker, I have not learned how to handle secrets the container needs to run upon other things  

## TODO List (Docker)
- [ ] Learn how to manage secrets properly (Docker Compose?)
- [ ] Write a Dockerfile 
- [ ] Test and make sure everything works
- [ ] Publish code + Publish to Docker Hub and GitHub Containers
- [ ] Write Documentation

## TODO List (Kubernetes)
- [ ] Finish this TODO list in the future
